### ISSUE TITLE
It does not work with Eufy Robovac X8 pro

### ISSUE THREAD

**Issue by p2923260** [CodeFoodPixels/robovac#103]
Added integration and login credential, it discovers the robot but only retrieve one unavailable entity (battery level). No other entities.

**Comment by McFarTech** [comment]
I have an X8 Pro SES as well and like you its only finding the batter which is showing as unavailable

**Comment by mainTAP** [comment]
X8 pro integration would be very appreciated

**Comment by p2923260** [comment]
Anyone still managing this integration? It's not serious handling it this way...

**Comment by HMside** [comment]
I also have a X8 Pro SES and in the log appears:

_Logger: homeassistant.components.vacuum
Quelle: helpers/entity_platform.py:366
Integration: Staubsauger (Dokumentation, Probleme)
Erstmals aufgetreten: 22:37:05 (7 Vorkommnisse)
Zuletzt protokolliert: 22:53:42

Error while setting up robovac platform for vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/robovac/vacuum.py", line 116, in async_setup_entry
    entity = RoboVacEntity(item)
  File "/config/custom_components/robovac/vacuum.py", line 284, in __init__
    self._attr_supported_features = self.vacuum.getHomeAssistantFeatures()
                                    ^^^^^^^^^^^
AttributeError: 'RoboVacEntity' object has no attribute 'vacuum'_

**Comment by J2-Tech** [comment]
Also fairly certain this relates to #68

**Comment by GeoCyberwolf** [comment]
Same here, is there any plans to add support? I am happy to help with any debugging or testing needed.
