### ISSUE TITLE
Unexpected Error on Login

### ISSUE THREAD

**Issue by jwilldwill** [CodeFoodPixels/robovac#11]
Just added this integration into HACS and upon login I receive "Unexpected Error"
![Screenshot 2023-08-17 at 5 15 57 PM](https://github.com/CodeFoodPixels/robovac/assets/142545478/bd2d1133-7b6e-4d1f-94e9-546a6bf78c3d)

**Comment by CodeFoodPixels** [comment]
Is there anything in the logs?

**Comment by jwilldwill** [comment]
How would I find the log for this?

**Comment by jwilldwill** [comment]
This error originated from a custom integration.

Logger: custom_components.robovac.config_flow
Source: custom_components/robovac/tuyawebapi.py:165
Integration: Eufy Robovac (documentation, issues)
First occurred: 6:52:13 PM (1 occurrences)
Last logged: 6:52:13 PM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/robovac/config_flow.py", line 130, in async_step_user
    valid_data = await validate_input(self.hass, user_input)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/robovac/config_flow.py", line 112, in validate_input
    await hass.async_add_executor_job(get_eufy_vacuums, data)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/robovac/config_flow.py", line 102, in get_eufy_vacuums
    for home in tuya_client.list_homes():
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/robovac/tuyawebapi.py", line 216, in list_homes
    return self._request(action="tuya.m.location.list", version="2.1")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/robovac/tuyawebapi.py", line 141, in _request
    self.acquire_session()
  File "/config/custom_components/robovac/tuyawebapi.py", line 211, in acquire_session
    session_response = self.request_session(self.username, self.country_code)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/robovac/tuyawebapi.py", line 203, in request_session
    session_response = self._request(
                       ^^^^^^^^^^^^^^
  File "/config/custom_components/robovac/tuyawebapi.py", line 165, in _request
    raise Exception(
Exception: No 'result' key in the response - the entire response is {'t': 1692316332957, 'success': False, 'errorCode': 'USER_PASSWD_WRONG', 'status': 'error', 'errorMsg': 'Incorrect account ID or password'}.

**Comment by DerBaer1986** [comment]
Same here

**Comment by CodeFoodPixels** [comment]
This is the same as #2.

There's a fix in the latest beta release: https://github.com/CodeFoodPixels/robovac/releases/tag/v1.1.0.beta.1
