### ISSUE TITLE
AttributeError: 'coroutine' object has no attribute 'payload'

### ISSUE THREAD

**Issue by tyacko2** [CodeFoodPixels/robovac#32]
I've been noticing this issue showing up in home assistant since I upgraded to the latest version (1.1) of this repository.  Is there something I can do on my end to address this or does it require a bug fix?  This vacuum is as 30C Max.  This error shows up roughly once an hour in the log.

```
2023-10-05 06:14:13.571 ERROR (MainThread) [homeassistant.helpers.entity] Update for vacuum.living_room_vac fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 732, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 991, in async_device_update
    await self.async_update()
  File "/config/custom_components/robovac/vacuum.py", line 314, in async_update
    await self.vacuum.async_get()
  File "/config/custom_components/robovac/tuyalocalapi.py", line 706, in async_get
    await self.async_update_state(response)
  File "/config/custom_components/robovac/tuyalocalapi.py", line 740, in async_update_state
    self._dps.update(state_message.payload["dps"])
                     ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'coroutine' object has no attribute 'payload'
```

Here is the the version of Home Assistant I'm currently running:
Home Assistant 2023.10.0
Supervisor 2023.10.0
Operating System 10.5
Frontend 20231002.0 - latest

**Comment by JackBailey** [comment]
I'm getting the same error on 1.1.1, on a Eufy G30

**Comment by IvoryBalboa** [comment]
I'm also getting this error on 1.1.1 for my Eufy G20

**Comment by pete-mcneill** [comment]
Also getting this on 30C
