### ISSUE TITLE
Receiving errors after latest Home Assistant Update

### ISSUE THREAD

**Issue by tyacko2** [CodeFoodPixels/robovac#34]
Current Home Assistant Info:
Home Assistant 2023.10.3
Supervisor 2023.10.0
Operating System 11.0
Frontend 20231005.0 - latest

Since the upgrade to 2023.10.3 I've been receiving the following errors for this addon.  Any idea if this is a bug or something I need to fix in my setup?

====================================================================================
2023-10-14 04:33:11.656 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/robovac/tuyalocalapi.py", line 777, in _async_send
    await self.writer.drain()
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 378, in drain
    await self._protocol._drain_helper()
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 167, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/robovac/tuyalocalapi.py", line 777, in _async_send
    await self.writer.drain()
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 366, in drain
    raise exc
  File "/config/custom_components/robovac/tuyalocalapi.py", line 777, in _async_send
    await self.writer.drain()
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 366, in drain
    raise exc
  File "/config/custom_components/robovac/tuyalocalapi.py", line 777, in _async_send
    await self.writer.drain()
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 366, in drain
    raise exc
  File "/config/custom_components/robovac/tuyalocalapi.py", line 777, in _async_send
    await self.writer.drain()
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 366, in drain
    raise exc
  File "/config/custom_components/robovac/tuyalocalapi.py", line 777, in _async_send
    await self.writer.drain()
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 366, in drain
    raise exc
  File "/config/custom_components/robovac/tuyalocalapi.py", line 777, in _async_send
    await self.writer.drain()
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 366, in drain
    raise exc
  File "/config/custom_components/robovac/tuyalocalapi.py", line 777, in _async_send
    await self.writer.drain()
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 366, in drain
    raise exc
  File "/config/custom_components/robovac/tuyalocalapi.py", line 777, in _async_send
    await self.writer.drain()
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 366, in drain
    raise exc
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 1051, in write
    n = self._sock.send(data)
        ^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/robovac/tuyalocalapi.py", line 724, in _async_ping
    await self._async_send(message)
  File "/config/custom_components/robovac/tuyalocalapi.py", line 808, in _async_send
    await self._async_send(message, retries=retries - 1)
  File "/config/custom_components/robovac/tuyalocalapi.py", line 808, in _async_send
    await self._async_send(message, retries=retries - 1)
  File "/config/custom_components/robovac/tuyalocalapi.py", line 808, in _async_send
    await self._async_send(message, retries=retries - 1)
  [Previous line repeated 1 more time]
  File "/config/custom_components/robovac/tuyalocalapi.py", line 782, in _async_send
    raise ConnectionException(
custom_components.robovac.tuyalocalapi.ConnectionException: Connection to 367205002cf43232871d (192.168.223.190:6668) failed: [Errno 104] Connection reset by peer
2023-10-14 04:33:11.686 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/robovac/tuyalocalapi.py", line 777, in _async_send
    await self.writer.drain()
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 378, in drain
    await self._protocol._drain_helper()
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 167, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/robovac/tuyalocalapi.py", line 753, in _async_handle_message
    response_data = await self.reader.readuntil(MAGIC_SUFFIX_BYTES)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 641, in readuntil
    await self._wait_for_data('readuntil')
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 526, in _wait_for_data
    await self._waiter
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 1051, in write
    n = self._sock.send(data)
        ^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
2023-10-14 04:33:15.231 ERROR (SyncWorker_0) [homeassistant] Error doing job: Unclosed client session

**Comment by YR-ZR0** [comment]
Similar issue here
```
Platform: Docker
Core 2024.1.0.dev20231130
Frontend 20231130.0.dev
```

```
Logger: homeassistant.components.vacuum
Source: helpers/entity_platform.py:361
Integration: Vacuum (documentation, issues)
First occurred: 5:14:23 PM (1 occurrences)
Last logged: 5:14:23 PM

Error while setting up robovac platform for vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/robovac/vacuum.py", line 116, in async_setup_entry
    entity = RoboVacEntity(item)
             ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/robovac/vacuum.py", line 284, in __init__
    self._attr_supported_features = self.vacuum.getHomeAssistantFeatures()
                                    ^^^^^^^^^^^
AttributeError: 'RoboVacEntity' object has no attribute 'vacuum'
```

**Comment by dinan5** [comment]
Similar issue here.

Logger: py.warnings
Source: helpers/entity.py:701
First occurred: 7:14:56 AM (2 occurrences)
Last logged: 8:14:29 AM

/usr/src/homeassistant/homeassistant/helpers/entity.py:701: RuntimeWarning: coroutine 'Message.async_send' was never awaited return

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:698
First occurred: 7:14:56 AM (2 occurrences)
Last logged: 8:14:29 AM

Update for vacuum.eufy_robovac_g30 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 698, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 959, in async_device_update
    await self.async_update()
  File "/config/custom_components/robovac/vacuum.py", line 314, in async_update
    await self.vacuum.async_get()
  File "/config/custom_components/robovac/tuyalocalapi.py", line 706, in async_get
    await self.async_update_state(response)
  File "/config/custom_components/robovac/tuyalocalapi.py", line 739, in async_update_state
    if state_message.payload and state_message.payload["dps"]:
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'coroutine' object has no attribute 'payload'

**Comment by BNWEIN** [comment]
Similar issues here 

Logger: homeassistant
Source: custom_components/robovac/tuyalocalapi.py:753
Integration: Eufy Robovac ([documentation](https://github.com/codefoodpixels/robovac), [issues](https://github.com/codefoodpixels/robovac/issues))
First occurred: 10:16:52 (2 occurrences)
Last logged: 10:23:52

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/robovac/tuyalocalapi.py", line 753, in _async_handle_message
    response_data = await self.reader.readuntil(MAGIC_SUFFIX_BYTES)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 640, in readuntil
    await self._wait_for_data('readuntil')
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 525, in _wait_for_data
    await self._waiter
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 989, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by aidengindin** [comment]
Same issue here.

Current Home Assistant Info:
Core 2024.1.5
Supervisor 2023.12.1
Operating System 11.4
Frontend 20240104.0

```
Logger: homeassistant
Source: custom_components/robovac/tuyalocalapi.py:753
Integration: Eufy Robovac (documentation, issues)
First occurred: 7:47:09 PM (1 occurrences)
Last logged: 7:47:09 PM
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/config/custom_components/robovac/tuyalocalapi.py", line 753, in _async_handle_message
    response_data = await self.reader.readuntil(MAGIC_SUFFIX_BYTES)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 640, in readuntil
    await self._wait_for_data('readuntil')
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 525, in _wait_for_data
    await self._waiter
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 989, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
```
