### ISSUE TITLE
X9 adds correctly but doesn't work

### ISSUE THREAD

**Issue by OmenBoy** [CodeFoodPixels/robovac#43]
It shows up as unavailable immediately. I've added the IP and restarted but nothing works. If the X9 is not supported, are there any plans to add support? Thank you.

**Comment by ProstoSanja** [comment]
Same problem here, it identifies it correctly, but seems to have some problem in actually fetching the data from device. Screenshots and logs attached, tell me if there is anything I can do more to investigate. Can setups network proxies, etc, not a hassle. @CodeFoodPixels 
```log
2023-12-05 14:52:27.532 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration robovac which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-05 14:52:27.535 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration komfovent which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-05 14:53:44.984 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to {{REDACTED}} (192.168.2.58:6668): Message(0x9, b'', 0, <Device {{REDACTED}} (192.168.2.58:6668)>)
2023-12-05 14:53:45.016 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Received message from {{REDACTED}} (192.168.2.58:6668): Message(0x9, b'', 0, None)
2023-12-05 14:53:54.972 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to {{REDACTED}} (192.168.2.58:6668): Message(0xa, {'gwId': '{{REDACTED}}', 'devId': '{{REDACTED}}'}, 47283005, <Device {{REDACTED}} (192.168.2.58:6668)>)
2023-12-05 14:53:54.983 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Received message from {{REDACTED}} (192.168.2.58:6668): Message(0xa, {'dps': {'151': True, '156': True, '158': 'Standard', '159': True, '160': False, '161': 40, '163': 100}}, 47283005, None)
2023-12-05 14:53:54.984 INFO (MainThread) [custom_components.robovac.tuyalocalapi] Received updated state {{REDACTED}} (192.168.2.58:6668): {'151': True, '156': True, '158': 'Standard', '159': True, '160': False, '161': 40, '163': 100}
2023-12-05 14:53:54.988 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to {{REDACTED}} (192.168.2.58:6668): Message(0x9, b'', 0, <Device {{REDACTED}} (192.168.2.58:6668)>)
2023-12-05 14:53:54.994 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Received message from {{REDACTED}} (192.168.2.58:6668): Message(0x9, b'', 0, None)
2023-12-05 14:54:04.992 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to {{REDACTED}} (192.168.2.58:6668): Message(0x9, b'', 0, <Device {{REDACTED}} (192.168.2.58:6668)>)
2023-12-05 14:54:05.006 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Received message from {{REDACTED}} (192.168.2.58:6668): Message(0x9, b'', 0, None)
2023-12-05 14:54:14.973 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to {{REDACTED}} (192.168.2.58:6668): Message(0xa, {'gwId': '{{REDACTED}}', 'devId': '{{REDACTED}}'}, 47303006, <Device {{REDACTED}} (192.168.2.58:6668)>)
2023-12-05 14:54:14.995 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to {{REDACTED}} (192.168.2.58:6668): Message(0x9, b'', 0, <Device {{REDACTED}} (192.168.2.58:6668)>)
2023-12-05 14:54:15.027 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Received message from {{REDACTED}} (192.168.2.58:6668): Message(0xa, {'dps': {'151': True, '156': True, '158': 'Standard', '159': True, '160': False, '161': 40, '163': 100}}, 47303006, None)
2023-12-05 14:54:15.028 INFO (MainThread) [custom_components.robovac.tuyalocalapi] Received updated state {{REDACTED}} (192.168.2.58:6668): {'151': True, '156': True, '158': 'Standard', '159': True, '160': False, '161': 40, '163': 100}
2023-12-05 14:54:15.032 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Received message from {{REDACTED}} (192.168.2.58:6668): Message(0x9, b'', 0, None)
2023-12-05 14:54:18.185 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Disconnected from {{REDACTED}} (192.168.2.58:6668)
2023-12-05 14:54:18.191 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/robovac/tuyalocalapi.py", line 753, in _async_handle_message
    response_data = await self.reader.readuntil(MAGIC_SUFFIX_BYTES)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 637, in readuntil
    raise exceptions.IncompleteReadError(chunk, None)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of undefined expected bytes
2023-12-05 14:54:24.997 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Disconnected from {{REDACTED}} (192.168.2.58:6668)
```
<img width="1238" alt="image" src="https://github.com/CodeFoodPixels/robovac/assets/26527928/7af8e45e-6495-4e51-8f6a-8bec8723344e">

**Comment by stephanschn** [comment]
same here.

**Comment by fbricker** [comment]
Same here...

**Comment by sakbark** [comment]
Same here!

**Comment by infinitytec** [comment]
Same issue with my G32 Pro. However, it seems that the buttons on the vacuum widget still work, so the vacuum can be controlled, but the status is unknown.

This may be due to the vacuum being on a network that does not allow it to talk to the Internet.

**Comment by Davewarrington** [comment]
Any hope of newer models getting added soon :(

**Comment by CodeFoodPixels** [comment]
As part of the work I'm doing on the better-dps branch, I'm making it so that devices with different commands can be supported. I'd need people to contribute/test the commands for the vacuums though.

**Comment by OmenBoy** [comment]
I’d be happy to help. I have an X9 Pro.

**Comment by infinitytec** [comment]
I'd also be happy to help with the G32 Pro

**Comment by Melmoes** [comment]
Got the new branch installed but unfortunately the X9 Pro is not working yet, so assuming you haven't reached that bit yet as it's pre-release :)

**Comment by Thrasher2020** [comment]
As above, clean install with the v1.3.0-better-dps.1 version and it doesn't want to play with the X9. If you need any help with testing just let me know.

**Comment by Thrasher2020** [comment]
I made a few mods, I can get the status randomly, battery all the time and the suction mode. Can't control it and it also sends data to the Error DPS (but it makes no sense). Here's are the DPS I tried. When you dump them a lot aren't there so this a a mish mash of other posts all put together to not quite end up with a working solution!

`    commands = {
        RobovacCommand.START_PAUSE: 151,
        RobovacCommand.DIRECTION: {
            "code": 155,
            "values": ["forward", "back", "left", "right"],
        },
        RobovacCommand.MODE: {
            "code": 152,
            "values": ["auto", "SmallRoom", "Spot", "Edge", "Nosweep"],
        },
        RobovacCommand.STATUS: 153,
        RobovacCommand.RETURN_HOME: 173,
        RobovacCommand.FAN_SPEED: {
            "code": 158,
            "values": ["Pure","Standard","Turbo","Max"],
        },
        RobovacCommand.LOCATE: 160,
        RobovacCommand.BATTERY: 163,
        RobovacCommand.ERROR: 177,
`

**Comment by stephanschn** [comment]
Can I somehow support this work?

**Comment by maximoei** [comment]
I added the T2320, based on the config of my L60 SES to the forked branch [here](https://github.com/maximoei/robovac/tree/L60-support).
https://github.com/CodeFoodPixels/robovac/issues/85#issuecomment-2249935438

Happy to hear if it works and if any of you can support bringing it back into the main branch here

**Comment by Thrasher2020** [comment]
The T2320.py in the indicated repo is 4 months old?

**Comment by maximoei** [comment]
Try again 😊

**Comment by Thrasher2020** [comment]
Sadly all it does is give the current suction level and battery. Cannot control it and when it's cleaning it doesn't update anything other than the battery, so I guess the X9 is a very different beast under the hood. Anything I can supply to assist with debugging this?

**Comment by maximoei** [comment]
If you can set the loglevel to debug, can you share some log messages of the tuya state before, during and after cleaning?

**Comment by maximoei** [comment]
The X9 seems to use different parameters than the L60, probably because it does mopping. So hard to determine what is needed here
