### ISSUE TITLE
Errors with Robovac LR30 Hybrid

### ISSUE THREAD

**Issue by Stefan1408** [CodeFoodPixels/robovac#50]
EDIT / UPDTAE

i think i found the issue but i can´t solve this by myself.

i took a look at the file that Hacs downloaded an there a missing lines in the code. in the a bunch of lines. 
**### SEE HERE:**

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant
Source: custom_components/robovac/vacuum.py:362
Integration: Eufy Robovac (documentation, issues)
First occurred: 21:32:12 (13 occurrences)
Last logged: 21:32:16

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/robovac/tuyalocalapi.py", line 736, in async_gratuitous_update_state
    await self.update_entity_state_cb()
  File "/config/custom_components/robovac/vacuum.py", line 330, in pushed_update_handler
    self.update_entity_values()
  File "/config/custom_components/robovac/vacuum.py", line 362, in update_entity_values
    self._attr_consumables = ast.literal_eval(
                             ^^^^^^^^^^^^^^^^^
KeyError: 'consumable'

**### AND HERE:**

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:898
First occurred: 21:32:16 (1 occurrences)
Last logged: 21:32:16

Update for vacuum.robovac_horst fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 898, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1216, in async_device_update
    await self.async_update()
  File "/config/custom_components/robovac/vacuum.py", line 316, in async_update
    self.update_entity_values()
  File "/config/custom_components/robovac/vacuum.py", line 362, in update_entity_values
    self._attr_consumables = ast.literal_eval(
                             ^^^^^^^^^^^^^^^^^
KeyError: 'consumable'

I tried to delete the HACS REPO - restart HA FULL - Restart HA by switching off and on the power button - get a new Download wich is 1.1.1 (same as i got before) - did the whole setup again - reboot - reboot AND the same error in the Logs. 

Am i doing it all wrong or is it a bug wich i created by myself in HA ?!

Hello there, 

I´m getting the following Errors in the HA Log while using this HACS Repositorie:

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:898
First occurred: 04:00:34 (2 occurrences)
Last logged: 04:01:54

Update for vacuum.robovac_horst fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 898, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1216, in async_device_update
    await self.async_update()
  File "/config/custom_components/robovac/vacuum.py", line 314, in async_update
    await self.vacuum.async_get()
  File "/config/custom_components/robovac/tuyalocalapi.py", line 706, in async_get
    await self.async_update_state(response)
  File "/config/custom_components/robovac/tuyalocalapi.py", line 739, in async_update_state
    if state_message.payload and state_message.payload["dps"]:
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'coroutine' object has no attribute 'payload'

### **AND**

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant
Source: custom_components/robovac/tuyalocalapi.py:782
Integration: Eufy Robovac (documentation, issues)
First occurred: 04:01:52 (1 occurrences)
Last logged: 04:01:52

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/robovac/tuyalocalapi.py", line 777, in _async_send
    await self.writer.drain()
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 377, in drain
    await self._protocol._drain_helper()
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 166, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/robovac/tuyalocalapi.py", line 777, in _async_send
    await self.writer.drain()
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 365, in drain
    raise exc
  File "/config/custom_components/robovac/tuyalocalapi.py", line 777, in _async_send
    await self.writer.drain()
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 365, in drain
    raise exc
  File "/config/custom_components/robovac/tuyalocalapi.py", line 777, in _async_send
    await self.writer.drain()
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 365, in drain
    raise exc
  File "/config/custom_components/robovac/tuyalocalapi.py", line 777, in _async_send
    await self.writer.drain()
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 365, in drain
    raise exc
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 1051, in write
    n = self._sock.send(data)
        ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/robovac/tuyalocalapi.py", line 724, in _async_ping
    await self._async_send(message)
  File "/config/custom_components/robovac/tuyalocalapi.py", line 808, in _async_send
    await self._async_send(message, retries=retries - 1)
  File "/config/custom_components/robovac/tuyalocalapi.py", line 808, in _async_send
    await self._async_send(message, retries=retries - 1)
  File "/config/custom_components/robovac/tuyalocalapi.py", line 808, in _async_send
    await self._async_send(message, retries=retries - 1)
  [Previous line repeated 1 more time]
  File "/config/custom_components/robovac/tuyalocalapi.py", line 782, in _async_send
    raise ConnectionException(
custom_components.robovac.tuyalocalapi.ConnectionException: Connection to bf458d7ba2a1e05265puts (10.10.1.102:6668) failed: [Errno 32] Broken pipe

### **AND**

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant
Source: custom_components/robovac/tuyalocalapi.py:753
Integration: Eufy Robovac (documentation, issues)
First occurred: 04:00:45 (2 occurrences)
Last logged: 04:01:49

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/robovac/tuyalocalapi.py", line 753, in _async_handle_message
    response_data = await self.reader.readuntil(MAGIC_SUFFIX_BYTES)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 637, in readuntil
    raise exceptions.IncompleteReadError(chunk, None)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of undefined expected bytes

I am really new to the HA Ecosystem , so i don´t have any clue where to start searching for the things i am missing. I did exactly the steps wich whre written in HACS 

System Version is :
Core
2024.1.5
Supervisor
2023.12.1
Operating System
11.4
Frontend
20240104.0

Running on RPI 3B

if this is not the right place to ask for help, please guide me to the right place.

Thanks in advance :)

**Comment by Stefan1408** [comment]
Tried it again on a new blank HASSIO Installation, Same issues.

**Comment by Stefan1408** [comment]
found @MelleD  Version 1.1.5 it is working. 

Closed
