### ISSUE TITLE
Connection reset issues

### ISSUE THREAD

**Issue by CodeFoodPixels** [CodeFoodPixels/robovac#61]
@CodeFoodPixels still having issues on 1.2.4

[home-assistant_2024-03-01T15-34-55.387Z.log](https://github.com/CodeFoodPixels/robovac/files/14462978/home-assistant_2024-03-01T15-34-55.387Z.log)

```
2024-03-01 15:34:22.165 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connection reset
2024-03-01 15:34:22.167 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668): Message(0x9, b'', 0, <Device bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)>)
2024-03-01 15:34:22.167 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Retrying send due to error. Connection to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668) failed: [Errno 104] Connection reset by peer
2024-03-01 15:34:22.167 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connection reset
```

```
2024-03-01 15:34:22.417 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connection reset
2024-03-01 15:34:22.417 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668): Message(0x9, b'', 0, <Device bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)>)
2024-03-01 15:34:22.417 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Disconnected from bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-01 15:34:22.417 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] 1 failures. Most recent: Connection to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668) failed: [Errno 104] Connection reset by peer
2024-03-01 15:34:22.417 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connection reset
2024-03-01 15:34:31.765 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Processing queue. Current length: 1
2024-03-01 15:34:31.765 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668): Message(0x9, b'', 0, <Device bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)>)
2024-03-01 15:34:31.766 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connecting to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-01 15:34:31.783 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connection reset
```

_Originally posted by @FuturamaPhill in https://github.com/CodeFoodPixels/robovac/issues/57#issuecomment-1973404671_

**Comment by CodeFoodPixels** [comment]
@FuturamaPhill I've made another tweak and it's in 1.2.5

**Comment by FuturamaPhill** [comment]
@CodeFoodPixels 

Still getting below:
```
2024-03-01 19:25:54.482 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668): Message(0xa, {'gwId': 'bf4b0ace39a5f9f09ajma7', 'devId': 'bf4b0ace39a5f9f09ajma7'}, 41684429, <Device bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)>)
2024-03-01 19:25:54.482 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connecting to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-01 19:25:54.495 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connection reset: [Errno 104] Connection reset by peer
2024-03-01 19:25:54.495 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Disconnected from bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-01 19:25:54.586 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Processing queue. Current length: 1
2024-03-01 19:25:54.586 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668): Message(0x9, b'', 0, <Device bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)>)
2024-03-01 19:25:54.586 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connecting to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-01 19:25:54.604 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connection reset: [Errno 104] Connection reset by peer
2024-03-01 19:25:54.604 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Disconnected from bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-01 19:26:04.439 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Processing queue. Current length: 1
2024-03-01 19:26:04.439 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668): Message(0x9, b'', 0, <Device bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)>)
2024-03-01 19:26:04.439 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connecting to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-01 19:26:04.458 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connection reset: [Errno 104] Connection reset by peer
2024-03-01 19:26:04.458 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Disconnected from bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-01 19:26:14.515 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Processing queue. Current length: 1
2024-03-01 19:26:14.516 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668): Message(0x9, b'', 0, <Device bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)>)
2024-03-01 19:26:14.516 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connecting to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-01 19:26:14.534 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connection reset: [Errno 104] Connection reset by peer
2024-03-01 19:26:14.534 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Disconnected from bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-01 19:26:24.521 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Processing queue. Current length: 1
2024-03-01 19:26:24.521 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668): Message(0x9, b'', 0, <Device bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)>)
2024-03-01 19:26:24.521 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connecting to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-01 19:26:24.539 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connection reset: [Errno 104] Connection reset by peer
2024-03-01 19:26:24.539 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Disconnected from bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-01 19:26:34.474 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Processing queue. Current length: 1
2024-03-01 19:26:34.474 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668): Message(0x9, b'', 0, <Device bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)>)
2024-03-01 19:26:34.474 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connecting to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-01 19:26:34.492 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connection reset: [Errno 104] Connection reset by peer
2024-03-01 19:26:34.492 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Disconnected from bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-01 19:26:44.456 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Processing queue. Current length: 1
2024-03-01 19:26:44.456 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668): Message(0x9, b'', 0, <Device bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)>)
2024-03-01 19:26:44.456 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connecting to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-01 19:26:44.474 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connection reset: [Errno 104] Connection reset by peer
2024-03-01 19:26:44.474 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Disconnected from bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-01 19:26:54.412 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Processing queue. Current length: 1
2024-03-01 19:26:54.412 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668): Message(0xa, {'gwId': 'bf4b0ace39a5f9f09ajma7', 'devId': 'bf4b0ace39a5f9f09ajma7'}, 41744429, <Device bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)>)
2024-03-01 19:26:54.413 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connecting to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-01 19:26:54.426 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connection reset: [Errno 104] Connection reset by peer
2024-03-01 19:26:54.426 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Disconnected from bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-01 19:26:54.517 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Processing queue. Current length: 1
2024-03-01 19:26:54.517 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668): Message(0x9, b'', 0, <Device bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)>)
2024-03-01 19:26:54.518 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connecting to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-01 19:26:54.538 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connection reset: [Errno 104] Connection reset by peer
2024-03-01 19:26:54.538 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Disconnected from bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-01 19:27:04.480 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Processing queue. Current length: 1
2024-03-01 19:27:04.480 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668): Message(0x9, b'', 0, <Device bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)>)
2024-03-01 19:27:04.480 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connecting to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-01 19:27:04.498 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connection reset: [Errno 104] Connection reset by peer
2024-03-01 19:27:04.498 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Disconnected from bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
```

**Comment by CodeFoodPixels** [comment]
This now genuinely seems like an issue communicating properly with the
vacuum. What model do you have?

**Comment by FuturamaPhill** [comment]
I have the 15C MAX.

Just thought i'd test network connectivity and appears fine from my pc:
```
PS C:\> tnc 192.168.0.144 -port 6668

ComputerName     : 192.168.0.144
RemoteAddress    : 192.168.0.144
RemotePort       : 6668
InterfaceAlias   : WiFi
SourceAddress    : 192.168.0.84
TcpTestSucceeded : True


PS C:\> ping homeassistant.local

Pinging homeassistant [192.168.0.245] with 32 bytes of data:
Reply from 192.168.0.245: bytes=32 time=1ms TTL=64
Reply from 192.168.0.245: bytes=32 time=3ms TTL=64
Reply from 192.168.0.245: bytes=32 time=3ms TTL=64
Reply from 192.168.0.245: bytes=32 time=4ms TTL=64

Ping statistics for 192.168.0.245:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 1ms, Maximum = 4ms, Average = 2ms
```

**Comment by CodeFoodPixels** [comment]
Huh, I have the exact same vacuum without issue 🤔

A couple of ideas to try:
 - turn the vacuum on and off with the switch
 - delete and re-add the vacuum (not the integration)

**Comment by FuturamaPhill** [comment]
> Huh, I have the exact same vacuum without issue 🤔 A couple of ideas to try: - turn the vacuum on and off with the switch - delete and re-add the vacuum (not the integration)

Tried that already, power switch and I held down the button for 10sec+ to resetup the wifi, assume thats the deletion process unless i'm wrong?

**Comment by CodeFoodPixels** [comment]
No, go to the integration page (https://my.home-assistant.io/redirect/integration/?domain=robovac), click the 3 dots next to your vacuum and click delete. Then re-add it.

**Comment by FuturamaPhill** [comment]
@CodeFoodPixels Ah right apologies already tried that a few times but did it again just now same results: 

```
2024-03-01 21:29:31.163 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Processing queue. Current length: 1
2024-03-01 21:29:31.163 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668): Message(0xa, {'gwId': 'bf4b0ace39a5f9f09ajma7', 'devId': 'bf4b0ace39a5f9f09ajma7'}, 49101202, <Device bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)>)
2024-03-01 21:29:31.163 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connecting to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-01 21:29:31.178 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connection reset: [Errno 104] Connection reset by peer
2024-03-01 21:29:31.178 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Disconnected from bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-01 21:29:31.269 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Processing queue. Current length: 1
2024-03-01 21:29:31.269 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668): Message(0x9, b'', 0, <Device bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)>)
2024-03-01 21:29:31.269 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connecting to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-01 21:29:31.288 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connection reset: [Errno 104] Connection reset by peer
2024-03-01 21:29:31.288 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Disconnected from bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
```

**Comment by FuturamaPhill** [comment]
@CodeFoodPixels saw there was an update so downloaded and attached logs below:

```
2024-03-03 08:12:22.044 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Processing queue. Current length: 1
2024-03-03 08:12:22.044 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Sending to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668): Message(0xa, {'gwId': 'bf4b0ace39a5f9f09ajma7', 'devId': 'bf4b0ace39a5f9f09ajma7'}, 174072017, <Device bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)>)
2024-03-03 08:12:22.045 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Connecting to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-03 08:12:22.058 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Connection reset: [Errno 104] Connection reset by peer
2024-03-03 08:12:22.058 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Disconnected from bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-03 08:12:22.149 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Processing queue. Current length: 1
2024-03-03 08:12:22.149 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Sending to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668): Message(0x9, b'', 0, <Device bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)>)
2024-03-03 08:12:22.149 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Connecting to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-03 08:12:22.178 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Connection reset: [Errno 104] Connection reset by peer
2024-03-03 08:12:22.178 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Disconnected from bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-03 08:12:32.110 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Processing queue. Current length: 1
2024-03-03 08:12:32.110 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Sending to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668): Message(0x9, b'', 0, <Device bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)>)
2024-03-03 08:12:32.110 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Connecting to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-03 08:12:32.128 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Connection reset: [Errno 104] Connection reset by peer
2024-03-03 08:12:32.128 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Disconnected from bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-03 08:12:42.063 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Processing queue. Current length: 1
2024-03-03 08:12:42.063 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Sending to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668): Message(0x9, b'', 0, <Device bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)>)
2024-03-03 08:12:42.063 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Connecting to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-03 08:12:42.082 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Connection reset: [Errno 104] Connection reset by peer
2024-03-03 08:12:42.082 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Disconnected from bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
```

**Comment by CodeFoodPixels** [comment]
I've added a little more logging if you could try again please?

**Comment by FuturamaPhill** [comment]
@CodeFoodPixels 

```
2024-03-04 07:38:15.717 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Processing queue. Current length: 1

2024-03-04 07:38:15.717 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Sending to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668): Message(0xa, {'gwId': 'bf4b0ace39a5f9f09ajma7', 'devId': 'bf4b0ace39a5f9f09ajma7'}, 258425739, <Device bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)>)

2024-03-04 07:38:15.718 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Connecting to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)

2024-03-04 07:38:15.736 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Connection reset: [Errno 104] Connection reset by peer

Traceback (most recent call last):

File "/config/custom_components/robovac/tuyalocalapi.py", line 826, in _async_handle_message

await self._response_task

File "/usr/local/lib/python3.12/asyncio/streams.py", line 657, in readuntil

await self._wait_for_data('readuntil')

File "/usr/local/lib/python3.12/asyncio/streams.py", line 542, in _wait_for_data

await self._waiter

File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 999, in _read_ready__data_received

data = self._sock.recv(self.max_size)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

ConnectionResetError: [Errno 104] Connection reset by peer

2024-03-04 07:38:15.736 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Disconnected from bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)

2024-03-04 07:38:15.826 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Processing queue. Current length: 1

2024-03-04 07:38:15.826 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Sending to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668): Message(0x9, b'', 0, <Device bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)>)

2024-03-04 07:38:15.826 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Connecting to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)

2024-03-04 07:38:15.847 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Connection reset: [Errno 104] Connection reset by peer

Traceback (most recent call last):

File "/config/custom_components/robovac/tuyalocalapi.py", line 826, in _async_handle_message

await self._response_task

File "/usr/local/lib/python3.12/asyncio/streams.py", line 657, in readuntil

await self._wait_for_data('readuntil')

File "/usr/local/lib/python3.12/asyncio/streams.py", line 542, in _wait_for_data

await self._waiter

File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 999, in _read_ready__data_received

data = self._sock.recv(self.max_size)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

ConnectionResetError: [Errno 104] Connection reset by peer

2024-03-04 07:38:15.847 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Disconnected from bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)

2024-03-04 07:38:25.772 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Processing queue. Current length: 1

2024-03-04 07:38:25.772 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Sending to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668): Message(0x9, b'', 0, <Device bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)>)

2024-03-04 07:38:25.772 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Connecting to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)

2024-03-04 07:38:25.792 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Connection reset: [Errno 104] Connection reset by peer

Traceback (most recent call last):

File "/config/custom_components/robovac/tuyalocalapi.py", line 826, in _async_handle_message

await self._response_task

File "/usr/local/lib/python3.12/asyncio/streams.py", line 657, in readuntil

await self._wait_for_data('readuntil')

File "/usr/local/lib/python3.12/asyncio/streams.py", line 542, in _wait_for_data

await self._waiter

File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 999, in _read_ready__data_received

data = self._sock.recv(self.max_size)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

ConnectionResetError: [Errno 104] Connection reset by peer

2024-03-04 07:38:25.792 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Disconnected from bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
```

**Comment by CodeFoodPixels** [comment]
So I was able to replicate this by opening the eufy app on my phone before the integration started on HA, and I found this comment from someone on another project: https://github.com/clach04/python-tuya/issues/2#issuecomment-366799119

Do you have anything else connecting to the vacuum when trying this?

**Comment by FuturamaPhill** [comment]
> So I was able to replicate this by opening the eufy app on my phone before the integration started on HA, and I found this comment from someone on another project: [clach04/python-tuya#2 (comment)](https://github.com/clach04/python-tuya/issues/2#issuecomment-366799119)
> 
> Do you have anything else connecting to the vacuum when trying this?

I do use the app to control the vac but its not open 24/7 so would imagine if it can only communicate to one device at a time it would eventually disconnect from phone and connect to HA, I haven't connected anything else to it.

**Comment by FuturamaPhill** [comment]
Tried beta version to see if that made any difference but still getting below:

```
2024-03-08 00:49:48.816 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Processing queue. Current length: 1
2024-03-08 00:49:48.816 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Sending to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668): Message(0xa, {'gwId': 'bf4b0ace39a5f9f09ajma7', 'devId': 'bf4b0ace39a5f9f09ajma7'}, 579518852, <Device bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)>)
2024-03-08 00:49:48.816 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Connecting to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-08 00:49:48.836 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Connection reset: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/config/custom_components/robovac/tuyalocalapi.py", line 833, in _async_handle_message
    await self._response_task
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 657, in readuntil
    await self._wait_for_data('readuntil')
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 542, in _wait_for_data
    await self._waiter
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 999, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
2024-03-08 00:49:48.836 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf4b0ace39a5f9f09ajma7] Disconnected from bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-08 00:49:48.836 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/robovac/tuyalocalapi.py", line 848, in _async_handle_message
    await self.async_disconnect()
  File "/config/custom_components/robovac/tuyalocalapi.py", line 753, in async_disconnect
    await self.writer.wait_closed()
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 361, in wait_closed
    await self._protocol._get_close_waiter(self)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 999, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
```
