### ISSUE TITLE
Error with L70 Hybrid Vacuum 

### ISSUE THREAD

**Issue by imhotep** [CodeFoodPixels/robovac#65]
@CodeFoodPixels I've had issues with the last few versions (since 1.2.0 I think).
Error repeats itself while cleaning
<details>
<summary>
Logs
</summary>

```
home-assistant    | 2024-03-14 11:02:45.715 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
home-assistant    | Traceback (most recent call last):
home-assistant    |   File "/config/custom_components/robovac/tuyalocalapi.py", line 806, in async_gratuitous_update_state
home-assistant    |     await self.update_entity_state_cb()
home-assistant    |   File "/config/custom_components/robovac/vacuum.py", line 312, in pushed_update_handler
home-assistant    |     self.update_entity_values()
home-assistant    |   File "/config/custom_components/robovac/vacuum.py", line 336, in update_entity_values
home-assistant    |     self._tuya_command_codes[RobovacCommand.CLEANING_AREA]
home-assistant    |     ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant    | KeyError: <RobovacCommand.CLEANING_AREA: 'cleaning_area'>
```

</details>

Happy to help debug further.

**Comment by CodeFoodPixels** [comment]
Are you sure you're not on the 1.3 alphas?

**Comment by imhotep** [comment]
Positive

**Comment by CodeFoodPixels** [comment]
`_tuya_command_codes` doesn't appear in the 1.2 line, it's something I've added as part of the changes that are in the current alphas. I think somehow you're running those.

**Comment by imhotep** [comment]
@CodeFoodPixels perhaps HACS updated it by accident. I didn't think I had beta versions enabled. I downgraded to 1.2.4 and it seems ok so far.
