### ISSUE TITLE
15C max unavailable

### ISSUE THREAD

**Issue by sumofatguy** [CodeFoodPixels/robovac#67]
Hi,

I am running v1.28 with HAOS 2024.3.1. It successfully detects the 15C max when I log in with my Eufy credentials, but the device and entities are unavailable. It looks like it briefly detected the battery percentage once, but went back to unknown. I also set the IP address of the device in the configuration settings. The vacuum is still successfully on my network and controllable with the Eufy app. I don't see anything in the logs

This may be a 'me' issue configuring this integration

![image](https://github.com/CodeFoodPixels/robovac/assets/228393/a02efbd8-a8f5-4f40-969a-1a89fd979499)
![image](https://github.com/CodeFoodPixels/robovac/assets/228393/c8fcc6c8-2426-4fa8-82cf-5cef1ff4593c)
![image](https://github.com/CodeFoodPixels/robovac/assets/228393/a878869e-6526-4e9d-a1c3-9a2cecae31b5)

**Comment by CodeFoodPixels** [comment]
So this may be down to commands changing. If you're willing to test an
alpha version, could you give the 1.3-better-dps versions a go? I have a
15C max too, and it's been stable on that branch for a couple of weeks

**Comment by sumofatguy** [comment]
I'm more than willing to try alpha 1.3, but when I select any version other than 1.28 in HACS, it just selects 1.28 again. I'm fairly new to HA, my apologies. Can I manually install it?

![image](https://github.com/CodeFoodPixels/robovac/assets/228393/4f6d3cf9-bf08-453b-972c-43c338763f9f)

**Comment by KyleStilkey** [comment]
> I'm fairly new to HA, my apologies
> 
> I was able to install v1.3.0-better-dps.2, and I still have the same issue
> 
> ![image](https://private-user-images.githubusercontent.com/228393/314162250-e2389126-27d2-4669-aa4e-22aa8d8be529.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MDQ4MTcsIm5iZiI6MTcxMDkwNDUxNywicGF0aCI6Ii8yMjgzOTMvMzE0MTYyMjUwLWUyMzg5MTI2LTI3ZDItNDY2OS1hYTRlLTIyYWE4ZDhiZTUyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQwMzE1MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMjdiNzUwYTIwYjY0Yjc4NjNiMDBhMjZlNjllZjEyNjJhZTkwYzE1M2Y4NjAyYWNlNTBlZjRiYjM5NGQ0MmQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VbfO9TSAtZKEgnECmc2ef1781Z0GBEmt2i4D3i9IPtM) ![image](https://private-user-images.githubusercontent.com/228393/314163118-9a983649-b165-4a97-b2ee-d7c9a5675038.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MDQ4MTcsIm5iZiI6MTcxMDkwNDUxNywicGF0aCI6Ii8yMjgzOTMvMzE0MTYzMTE4LTlhOTgzNjQ5LWIxNjUtNGE5Ny1iMmVlLWQ3YzlhNTY3NTAzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQwMzE1MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTNjZDg3YjU4MDg1MDZjMjgwYWY4ZTIwYzI4ZjdiZWM0MzI0ZjgwOGJkNjc5MWEzZGIzNGJhYzY4NTQ1MjU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.r4iL96j9XS2IvjtDi6xCyDVLEfQl0ZbB6J0BBTO55DU)
> 
> ```
> 2024-03-19 11:22:57.180 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.ebd5e0a4ef002cb8demame] Processing queue. Current length: 1
> 2024-03-19 11:22:57.180 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.ebd5e0a4ef002cb8demame] Sending to ebd5e0a4ef002cb8demame (10.10.10.107:6668): Message(0x9, b'', 0, <Device ebd5e0a4ef002cb8demame (10.10.10.107:6668)>)
> 2024-03-19 11:22:57.181 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.ebd5e0a4ef002cb8demame] Connecting to ebd5e0a4ef002cb8demame (10.10.10.107:6668)
> 2024-03-19 11:22:57.201 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.ebd5e0a4ef002cb8demame] Connection reset: [Errno 104] Connection reset by peer
> Traceback (most recent call last):
>   File "/config/custom_components/robovac/tuyalocalapi.py", line 833, in _async_handle_message
>     await self._response_task
>   File "/usr/local/lib/python3.12/asyncio/streams.py", line 660, in readuntil
>     await self._wait_for_data('readuntil')
>   File "/usr/local/lib/python3.12/asyncio/streams.py", line 545, in _wait_for_data
>     await self._waiter
>   File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1003, in _read_ready__data_received
>     data = self._sock.recv(self.max_size)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ConnectionResetError: [Errno 104] Connection reset by peer
> 
> 2024-03-19 11:22:57.202 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.ebd5e0a4ef002cb8demame] Disconnected from ebd5e0a4ef002cb8demame (10.10.10.107:6668)
> 2024-03-19 11:22:57.202 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/config/custom_components/robovac/tuyalocalapi.py", line 848, in _async_handle_message
>     await self.async_disconnect()
>   File "/config/custom_components/robovac/tuyalocalapi.py", line 753, in async_disconnect
>     await self.writer.wait_closed()
>   File "/usr/local/lib/python3.12/asyncio/streams.py", line 364, in wait_closed
>     await self._protocol._get_close_waiter(self)
>   File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1003, in _read_ready__data_received
>     data = self._sock.recv(self.max_size)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ConnectionResetError: [Errno 104] Connection reset by peer
> ```

I had the same issue, for me I had to delete the vacuum cleaner and read it for it to start working again. Give that a shot and also I see you have auto discover off, see if you turn that option back on resolves it and double check your IP is correct as it looks like it's having a communication error with the device.

**Comment by sumofatguy** [comment]
What do you mean delete the vacuum clean and read it? I will try again with autodiscovery on, I just saw some comments in a different thread about conflicts with localtuya being installed and tried disabling autodiscovery to see if that would have any effect

**Comment by FuturamaPhill** [comment]
> What do you mean delete the vacuum cleaner and read it? I will try again with autodiscovery on, I just saw some comments in a different thread about conflicts with localtuya being installed and tried disabling autodiscovery to see if that would have any effect
> ![image](https://github.com/CodeFoodPixels/robovac/assets/228393/9093fef1-3d01-409c-85ce-7754adeeca66)

Not sure if it's of any relevance but I also a eufy WAP and having the issue

**Comment by m1dst** [comment]
I am using 1.3 dps and also agree it doesn't work for 15C and produces the same output as @FuturamaPhill receives.

```
Logger: homeassistant
Source: custom_components/robovac/tuyalocalapi.py:753
integration: Eufy Robovac ([documentation](https://github.com/codefoodpixels/robovac), [issues](https://github.com/codefoodpixels/robovac/issues))
First occurred: 11:06:03 (11 occurrences)
Last logged: 11:07:24

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/robovac/tuyalocalapi.py", line 848, in _async_handle_message
    await self.async_disconnect()
  File "/config/custom_components/robovac/tuyalocalapi.py", line 753, in async_disconnect
    await self.writer.wait_closed()
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 364, in wait_closed
    await self._protocol._get_close_waiter(self)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1003, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by djrarky** [comment]
I also confirm, 1.3-dps doesn't work for my 15C.
