### ISSUE TITLE
G20 unavailable

### ISSUE THREAD

**Issue by IvoryBalboa** [CodeFoodPixels/robovac#71]
`Logger: homeassistant.helpers.entity
Quelle: helpers/entity.py:945
Erstmals aufgetreten: 13:55:04 (1 Vorkommnisse)
Zuletzt protokolliert: 13:55:04

Update for vacuum.wall_e fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1262, in async_device_update
    await self.async_update()
  File "/config/custom_components/robovac/vacuum.py", line 302, in async_update
    await self.async_update_vacuum()
  File "/config/custom_components/robovac/vacuum.py", line 323, in async_update_vacuum
    self.update_entity_values()
  File "/config/custom_components/robovac/vacuum.py", line 354, in update_entity_values
    self._tuya_command_codes[RobovacCommand.CLEANING_AREA]
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: <RobovacCommand.CLEANING_AREA: 'cleaning_area'>
`

After upgrading to v1.3.0 my G20 is unavailable. Battery sensor does work, but the vacuum entity is unavailable

**Comment by CodeFoodPixels** [comment]
1.3.0 is currently an alpha, most vacuums will probably not work as it is still in active development
