### ISSUE TITLE
X8 Hybrid not working anymore

### ISSUE THREAD

**Issue by StormCh** [CodeFoodPixels/robovac#74]
cant control X8 Hybrid via HomeAssistant Automations. Lovelace Card shows wrong informations

```
Logger: homeassistant.helpers.entity
Quelle: helpers/entity.py:945
Erstmals aufgetreten: 26. März 2024 um 14:26:34 (4368 Vorkommnisse)
Zuletzt protokolliert: 15:02:21

Update for vacuum.robovac fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1262, in async_device_update
    await self.async_update()
  File "/config/custom_components/robovac/vacuum.py", line 302, in async_update
    await self.async_update_vacuum()
  File "/config/custom_components/robovac/vacuum.py", line 323, in async_update_vacuum
    self.update_entity_values()
  File "/config/custom_components/robovac/vacuum.py", line 354, in update_entity_values
    self._tuya_command_codes[RobovacCommand.CLEANING_AREA]
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: <RobovacCommand.CLEANING_AREA: 'cleaning_area'>

```

**Comment by StormCh** [comment]
```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant
Quelle: custom_components/robovac/tuyalocalapi.py:919
Integration: Eufy Robovac (Dokumentation, Probleme)
Erstmals aufgetreten: 27. März 2024 um 11:02:20 (14 Vorkommnisse)
Zuletzt protokolliert: 15:01:06

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/locks.py", line 386, in acquire
    await fut
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/robovac/tuyalocalapi.py", line 911, in async_recieve
    await self._recieve_task
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 519, in wait_for
    async with timeouts.timeout(timeout):
  File "/usr/local/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/robovac/vacuum.py", line 326, in async_forced_update
    await self.async_update_vacuum()
  File "/config/custom_components/robovac/vacuum.py", line 322, in async_update_vacuum
    await self.vacuum.async_get()
  File "/config/custom_components/robovac/tuyalocalapi.py", line 763, in async_get
    response = await self.async_recieve(message)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/robovac/tuyalocalapi.py", line 919, in async_recieve
    del self._listeners[message.sequence]
        ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 74526006

```

**Comment by StormCh** [comment]
Same problem with v.1.2.11
