### ISSUE TITLE
Neither G30 or X8 pro are working

### ISSUE THREAD

**Issue by gabriel403** [CodeFoodPixels/robovac#76]
I've got a G30 and an X8 pro SES, but unfortunately neither are working. The batteries show up as entities, but have a red exclamation next to them, no vacuum commands show up for either of them

I know the X8 is unsupported but the G30 is a bit older and I thought it might be ok

```
2024-04-03 17:19:13.380 ERROR (MainThread) [homeassistant.components.vacuum] Error while setting up robovac platform for vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 350, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/robovac/vacuum.py", line 116, in async_setup_entry
    entity = RoboVacEntity(item)
             ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/robovac/vacuum.py", line 284, in __init__
    self._attr_supported_features = self.vacuum.getHomeAssistantFeatures()
                                    ^^^^^^^^^^^
AttributeError: 'RoboVacEntity' object has no attribute 'vacuum'
2024-04-03 17:19:14.967 ERROR (MainThread) [homeassistant.components.vacuum] Error while setting up robovac platform for vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 350, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/robovac/vacuum.py", line 116, in async_setup_entry
    entity = RoboVacEntity(item)
             ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/robovac/vacuum.py", line 284, in __init__
    self._attr_supported_features = self.vacuum.getHomeAssistantFeatures()
                                    ^^^^^^^^^^^
AttributeError: 'RoboVacEntity' object has no attribute 'vacuum'
2024-04-03 17:19:14.975 DEBUG (MainThread) [custom_components.robovac] Updated ip address of bf02ba63383f021ebacauw to 192.168.0.110
2024-04-03 17:19:56.094 ERROR (MainThread) [homeassistant.components.vacuum] Error while setting up robovac platform for vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 350, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/robovac/vacuum.py", line 116, in async_setup_entry
    entity = RoboVacEntity(item)
             ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/robovac/vacuum.py", line 284, in __init__
    self._attr_supported_features = self.vacuum.getHomeAssistantFeatures()
                                    ^^^^^^^^^^^
AttributeError: 'RoboVacEntity' object has no attribute 'vacuum'
```

**Comment by mainTAP** [comment]
X8 Pro integration would be very appreciated

**Comment by Daafip** [comment]
I have the same issue where the X8 Pro doesn't show up. Anything we can do to add to compatibility ?

**Comment by maximoei** [comment]
https://github.com/CodeFoodPixels/robovac/issues/46#issuecomment-2257804448
