### ISSUE TITLE
X8 Error adding entity

### ISSUE THREAD

**Issue by llamafarmer-alex** [CodeFoodPixels/robovac#77]
Integration has been working with no issues for about 8 months now. I've noticed that my automations to clean at certain times have been failing. Ive tried readding/deleting etc but im met with this error now. Any ideas? 

> Error adding entity vacuum.dobby for domain vacuum with platform robovac
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 580, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 881, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1333, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/robovac/vacuum.py", line 297, in async_added_to_hass
    await self.async_forced_update()
  File "/config/custom_components/robovac/vacuum.py", line 326, in async_forced_update
    await self.async_update_vacuum()
  File "/config/custom_components/robovac/vacuum.py", line 323, in async_update_vacuum
    self.update_entity_values()
  File "/config/custom_components/robovac/vacuum.py", line 354, in update_entity_values
    self._tuya_command_codes[RobovacCommand.CLEANING_AREA]
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: <RobovacCommand.CLEANING_AREA: 'cleaning_area'>

**Comment by xhemp** [comment]
Try an earlier version (mine works fine with 1.1.1)

**Comment by jonshorter** [comment]
Seconded
