### ISSUE TITLE
Support for L60 SE

### ISSUE THREAD

**Issue by meanandpinchy** [CodeFoodPixels/robovac#85]
The unit is detected, but has no entities except for battery, which is "unavailable". Please add support for the L60 SE.

**Comment by mumpers68** [comment]
I second the support for the L60 SES!

**Comment by stoozak** [comment]
yes, please!

**Comment by Harm-Veraa** [comment]
I was looking into this, seems the TUYA_CODES are incorrect for this robovac. Yet to firgure out any of the codes, except for battery life, which is 163. Is there any documentation about these codes available?

**Comment by stoozak** [comment]
> ,

Where do we plug these in? Happy to test and feedback.

**Comment by Harm-Veraa** [comment]
Depends if you have main branch or better-dps branch. For main branch they are at the top of the 'vacuum' file, if I am not mistaken (currently on the other branch). On better-dps branch they are at the specific file for your vacuum. In our case this is T2278 (or at least for me, I have the hybrid, not sure if it's different but otherwise I expect T2277). 

In both cases, before it will even load, you need to add your vacuum. In the better-dps branch you copy the specific model file and add it to the list of vacs in __init__. In the main you can check the robovac file and add it to the list of 'L' models. 

If you are on better-dps branch, also make sure to make a comment for extra features (as they crash currently, possible because code is incorrect, not sure). 

    robovac_features = 0; # RoboVacEntityFeature.CLEANING_TIME | RoboVacEntityFeature.CLEANING_AREA | RoboVacEntityFeature.DO_NOT_DISTURB | RoboVacEntityFeature.AUTO_RETURN | RoboVacEntityFeature.ROOM | RoboVacEntityFeature.ZONE | RoboVacEntityFeature.BOOST_IQ | RoboVacEntityFeature.MAP | RoboVacEntityFeature.CONSUMABLES


After all of this, a logger can be added to log everything. If you change the code of the battery to 161, you'll see that one works in the home panel.

**Comment by Harm-Veraa** [comment]
It's curious, if I start the robot or do something with it, the status does not change according to the Logger. Perhaps another api call is required?

**Comment by Harm-Veraa** [comment]
Should the developer read this, and willing to look into it. Some more messages from the device, when I start it via the Eufy app. It looks like it's encrypted...

{'151': True, '156': True, '158': 'Turbo', '159': True, '160': False, '161': 41, '163': 99, '177': 'DAjZhNCLlIztzgFSAA==', '153': 'BBADGgA=', '178': 'DQiuzqvylIztzgESAR8=', '152': 'AggG', '179': 'FhIUEhIIEBABIGMozsPsswYwgcTsswY=', '173': 'GAoSMgoKAggBEgQIARgPOgQKAggBEgIIAQ==', '176': 'JgoAGgBSCBoAIgIIASoAWDBiFAoSCghOcjE4X0lvVBoGEKnC7LMG', '169': 'egoZZXVmeSBDbGVhbiBMNjAgSHlicmlkIFNFUxoRMkM6QzM6RTY6NTk6RkI6NUEiBjEuMy4yNCgFQihhMWNjNDM0Y2RiYzFkNWM0MmRmYWY3NGEyNGY3NWRkNzQxYzg1YTNlYhYIARIECAIQARoECAIQASICCAEqAggB'}

**Comment by Harm-Veraa** [comment]
I also get this error sometimes, seems to be when I clicked a button and then the sequence number goes haywire.. Not sure tho. In any case, the last  3 messages show it is working. At least the communication part is.. Can you try 163 for battery? That is what I have currently.

**Comment by Harm-Veraa** [comment]
One thing to add. Battery wont show in a default card (when the device is so-called offline). Go to the device info itself under settings -> devices. Should show there.

**Comment by stoozak** [comment]
Hmmm, no luck. It still shows 0%. I also don't seem to get the log state with the encrypted numbers that you got.

**Comment by Harm-Veraa** [comment]
Did you enable debug logging?

**Comment by stoozak** [comment]
Afraid so :(

**Comment by Harm-Veraa** [comment]
Mhh okay odd. I don't know why it won't work for you.. when I have more time I might look into it further. Should I find a proper solution I'll see if I can create a PR

**Comment by stoozak** [comment]
Some of these codes may be helpful: https://github.com/CodeFoodPixels/robovac/issues/42#issuecomment-1873242870

**Comment by JohnD76** [comment]
+ 1 for the LS60 SES integration please.

**Comment by JohnD76** [comment]
I am having similar issues, my L60SES replaces a 15C MAX. I have removed the Eufy integration from HACS and rebooted. Amended the robots file to include the T2277 model number and when adding a device for some reason it identifies the L^0SES and the name of the robot, burt gives it the MAC address of the old robot (15C MAX), even though this is removed from the Eufy app.....

I can' control the robot or see the battery status sadly via HA.

**Comment by Harm-Veraa** [comment]
Nice! How did you find out the codes?

**Comment by IainPHay** [comment]
This is great to see, I have cleaned out the old integration and installed this but I still only see just the battery entity. I just have the L60

**Comment by maximoei** [comment]
> This is great to see, I have cleaned out the old integration and installed this but I still only see just the battery entity. I just have the L60

Sometimes it only starts reporting detailed state after I start (and stop) a cleaning cycle from the app. After that, session seems to 'stick'

**Comment by IainPHay** [comment]
Thanks for the feedback, must admit I'd not thought of triggering it via the app. I'll give that a try and see if it grabs the info

**Comment by asportnoy** [comment]
Was able to get my L60 SES (T2277) working on your fork. Nice work! Will test a full run later tonight.

Had to make 2 minor changes to get it running:
- Add the model to `vacuums/__init__.py`, was previously missing
- `vaccuums/T2267.py` had the wrong class name causing an import error - updated it to match the file name

**Comment by IainPHay** [comment]
> Was able to get my L60 SES (T2277) working on your fork. Nice work! Will test a full run later tonight.
> 
> Had to make 2 minor changes to get it running:
> 
> * Add the model to `vacuums/__init__.py`, was previously missing
> * `vaccuums/T2267.py` had the wrong class name causing an import error - updated it to match the file name

That second bit helped me out, thanks! I have it running now but it always shows error despite being controllable but it's a massive improvement on just having the battery status :)

**Comment by jb123567** [comment]
> > Was able to get my L60 SES (T2277) working on your fork. Nice work! Will test a full run later tonight.
> 
> > 
> 
> > Had to make 2 minor changes to get it running:
> 
> > 
> 
> > * Add the model to `vacuums/__init__.py`, was previously missing
> 
> > * `vaccuums/T2267.py` had the wrong class name causing an import error - updated it to match the file name
> 
> 
> 
> That second bit helped me out, thanks! I have it running now but it always shows error despite being controllable but it's a massive improvement on just having the battery status :)

I'm having the L60 remaining unavailable, what exactly did you change in the file?

**Comment by asportnoy** [comment]
[The latest commit](https://github.com/maximoei/robovac/commit/fc1d0f58ca31a7481f9e99e13cb27a3ff8e510cf) on that fork includes fixes for the issues I mentioned, so you shouldn't have to manually change anything anymore. Make sure that you have the correct fork/branch checked out and you pulled the latest commit. If so, check the logs in home assistant.

**Comment by jb123567** [comment]
> [The latest commit](https://github.com/maximoei/robovac/commit/fc1d0f58ca31a7481f9e99e13cb27a3ff8e510cf) on that fork includes fixes for the issues I mentioned, so you shouldn't have to manually change anything anymore. Make sure that you have the correct fork/branch checked out and you pulled the latest commit. If so, check the logs in home assistant.

Yep, realised just after posting, HA had done something weird with the files. Started again completely and now working happily. Did have to start the device in the app to get it to register.

**Comment by asportnoy** [comment]
Full test run was mostly successful! I did notice one issue though: when I checked the logs afterwords, it looks like it was intermittently unavailable while it was running. Based on the timings, my guess is that this was when it returned to the base to empty at cut hair, but I was not actually there so I can't confirm. Nothing in the logs. Not a huge deal but definitely worth making a note of at least.

![image](https://github.com/user-attachments/assets/0e3fb3fe-bd84-4642-945b-b87f8640d7a4)

**Comment by asportnoy** [comment]
Hi all, a few updates from my continued testing (on my L60 SES) over the last week or so:

- A new software update was available for on vacuum. As far as I can tell, it works just as it did before, so should be safe to update your vacuums.
- The unknown status issue mentioned in my last comment was in fact when the vacuum returns home to empty itself as I suspected.
- I noticed in HA that I can pause the vacuum just fine, but resuming it does not do anything.
- "Do not disturb" in the attributes section is showing as "DgoAEgoKABICCBYaAggI", which I think is another message that needs handling. It is currently disabled for me.

Besides those issues, it seems to work fine! Might be good to clean up a bit as needed and create a PR now, and then come back for whatever other issues there are since this is definitely a huge improvement over what's currently available.

\* This was all done on commit [fc1d0f5](https://github.com/maximoei/robovac/tree/fc1d0f58ca31a7481f9e99e13cb27a3ff8e510cf). I just noticed there are some new commits, so I will pull and test those later.

**Comment by blablazzz** [comment]
how can i start using it? With latest integration version i still dont see my L60 vac.

**Comment by maximoei** [comment]
It is not in the latest integration, you need to use [this fork](https://github.com/maximoei/robovac/tree/L60-support) for now

**Comment by DesertNomadBear** [comment]
I have an L60, added the latest repository, started and stopped the vacuum from the Eufy app, but I’m still only seeing the battery sensor (with no battery value), and I’m getting this error:

Error while setting up robovac platform for vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/robovac/vacuum.py", line 116, in async_setup_entry
    entity = RoboVacEntity(item)
             ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/robovac/vacuum.py", line 284, in __init__
    self._attr_supported_features = self.vacuum.getHomeAssistantFeatures()
                                    ^^^^^^^^^^^
AttributeError: 'RoboVacEntity' object has no attribute 'vacuum'

**Comment by plainmad** [comment]
Ive got an l60 hybrid and I've tried the new fork but it doesn't seem to be working? 
Looking at the comments above we seek to have the models of l60, l60 se, l60 se hybrid but not just the l60 hybrid so I assume this is why my one isn't working. 

If it is able to be added that would be great and I'm happy to helping with any logs etc needed

**Comment by Yorin1** [comment]
> It is not in the latest integration, you need to use [this fork](https://github.com/maximoei/robovac/tree/L60-support) for now

I am a little lost on how to install this modified integration for the L60 SES.  From the page linked above I used "https://github.com/maximoei/robovac.git" as a custom repository on HACS and then I follow the normal steps for setting up the integration.  This doesn't work. In Home Assistant the folder "vacuums" is not created under "custom_components/robovac".  The log wil show an error setting up the Robovac platform and the integration will show 1 device with an unavailable battery entity.

I'm a little out of my depth here. What are the steps to follow in order to install a fork or a certain commit?  Can this be done from the HACS UI or do I need to SSH into my HA instance? Thanks to whoever can point me in the right direction. I will not rest until I can control my L60 SES vacuum from within HA :-)

**Comment by asportnoy** [comment]
You need to check out the L60-support branch, which I don't think you can do from HACS.

In my case, I cloned it and installed it in the custom components folder manually (via terminal).

**Comment by Yorin1** [comment]
> You need to check out the L60-support branch, which I don't think you can do from HACS.
> 
> In my case, I cloned it and installed it in the custom components folder manually (via terminal).

I started in "https://github.com/maximoei/robovac/tree/L60-support" and hit the green "code" button. I now have the files on my HD (using Git desktop). I copied the contents from "custom_components/robovac" into the HA "custom_components/robovac" folder (using the "file editor" add-on) and rebooted HA. However after adding the integration it is again the same issue (error in the log and just the not available battery entity).

When you say you installed it in custom components manually, do you mean you copied the files to that folder or is there more to it? Also besides the folder "custom_components" there are other files and folders that come with the clone. Do you have to do anything with those or does only the folder "custom_components" matter?

**Comment by asportnoy** [comment]
Check the `custom_components/robovac/vacuums` folder and look for a `T2277.py` file. If it's not there, it means you're not actually on the correct branch.

If you _are_ actually on the correct branch, I need to see the file tree to understand how you did it. Also make sure you uninstalled the prior version first to make sure they're not conflicting and still using the old version somehow.

**Comment by Yorin1** [comment]
> Check the `custom_components/robovac/vacuums` folder and look for a `T2277.py` file. If it's not there, it means you're not actually on the correct branch.
> 
> If you _are_ actually on the correct branch, I need to see the file tree to understand how you did it. Also make sure you uninstalled the prior version first to make sure they're not conflicting and still using the old version somehow.

Thanks a lot! You pointed me to where I got it wrong with your comments.

For anybody who might be struggling with this as well. I used GitHub Desktop to open the Robovac repository, then selected the right branch (this is where I went wrong before). If you then hit "show in explorer" you are taken to all the files. Copy everything under "custom_components" to the same directory in your HA instance and reboot (I used the file editor add-on in HA to copy files from my HD to the RPi 4 that runs my HA). After rebooting you search for the Robovac integration and once it's added you need to start a cleaning run from the Eufy app to have the device become active in HA.

Not really that hard once you figure out what to do. Copying all the files one-by-one was a bit tedious, but this only needs to be done once. I suppose that using the terminal there are easier ways to copy the files at once.

**Comment by pnm1977** [comment]
> It is not in the latest integration, you need to use [this fork](https://github.com/maximoei/robovac/tree/L60-support) for now

@maximoei - Any idea if it's possible to send the do not disturb command for on and off on this fork and have you managed to work out how it's done? The entity seems stable when controlling the on/off via the app and the string is unique based on the set schedule in the app.

**Comment by Casper9228** [comment]
@maximoei Hoi!
I was wondering if you could give me a push into the right direction, although hijacking this issue a little bit. I have a X8 Pro SES (T2276G11) that I was hoping to set up with your L60 branch. Unfortunately, after two days of tinkering, I just don't seem to be able to set it up.... This is my error log:

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/robovac/tuyalocalapi.py", line 911, in async_recieve
    await self._recieve_task
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 519, in wait_for
    async with timeouts.timeout(timeout):
  File "/usr/local/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 595, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 909, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1365, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/robovac/vacuum.py", line 366, in async_added_to_hass
    await self.async_forced_update()
  File "/config/custom_components/robovac/vacuum.py", line 395, in async_forced_update
    await self.async_update_vacuum()
  File "/config/custom_components/robovac/vacuum.py", line 391, in async_update_vacuum
    await self.vacuum.async_get()
  File "/config/custom_components/robovac/tuyalocalapi.py", line 763, in async_get
    response = await self.async_recieve(message)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/robovac/tuyalocalapi.py", line 923, in async_recieve
    raise ResponseTimeoutException(
custom_components.robovac.tuyalocalapi.ResponseTimeoutException: Timed out waiting for response to sequence number 384152823
2024-09-10 19:52:44.997 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf176e865fc470ad656htu] Disconnected from bf176e865fc470ad656htu (192.168.1.225:6668)
2024-09-10 19:52:45.000 DEBUG (MainThread) [custom_components.robovac.vacuum] ['Quiet', 'Standard', 'Turbo', 'Max']
2024-09-10 19:52:45.002 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf176e865fc470ad656htu] Processing queue. Current length: 1
2024-09-10 19:52:45.003 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf176e865fc470ad656htu] Sending to bf176e865fc470ad656htu (192.168.1.225:6668): Message(0xa, {'gwId': 'bf176e865fc470ad656htu', 'devId': 'bf176e865fc470ad656htu'}, 384186211, <Device bf176e865fc470ad656htu (192.168.1.225:6668)>)
2024-09-10 19:52:45.003 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf176e865fc470ad656htu] Connecting to bf176e865fc470ad656htu (192.168.1.225:6668)
2024-09-10 19:52:45.112 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf176e865fc470ad656htu] Processing queue. Current length: 1
2024-09-10 19:52:45.112 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf176e865fc470ad656htu] Sending to bf176e865fc470ad656htu (192.168.1.225:6668): Message(0x9, b'', 0, <Device bf176e865fc470ad656htu (192.168.1.225:6668)>)
2024-09-10 19:52:45.130 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi.bf176e865fc470ad656htu] Incomplete read
```

If you have some spare time, could you please have a look? :)

Many thanks!

**Comment by avidricaire** [comment]
I followed the instructions and the device is detected and it can read its states (charging, cleaning, docked), but I have no controls in HA and it just says the entity is unavailable. Any ideas? When added to Alexa through HA cloud I can control it

**Comment by avidricaire** [comment]
> > I followed the instructions and the device is detected and it can read its states (charging, cleaning, docked), but I have no controls in HA and it just says the entity is unavailable. Any ideas? When added to Alexa through HA cloud I can control it
> 
> I think there is a bug where the initial state is always unavailable when you first set it up. Try using the official app to start a cleaning cycle, then see if the controls in HA start working.

Took a little bit but that solved it, thank you!

**Comment by maximoei** [comment]
> > I followed the instructions and the device is detected and it can read its states (charging, cleaning, docked), but I have no controls in HA and it just says the entity is unavailable. Any ideas? When added to Alexa through HA cloud I can control it
> 
> I think there is a bug where the initial state is always unavailable when you first set it up. Try using the official app to start a cleaning cycle, then see if the controls in HA start working.

Yes, this is because the vaccuum only starts reporting it's detailed state after start/stop of a cleaning cycle from the app, before that, no data is available and therefore the entity is also unavailable. After that initial use of the app the 'session' sticks, also in HA.

**Comment by asportnoy** [comment]
I'm not sure if that's the case. When you open the Eufy app, it knows it's connected and available right away and is able to load all that detailed information. Maybe some other API you need to implement?

Regardless, I think it might be a better UX to assume it's available when the device is set up initially. The UI controls are disabled if it's unavailable, which gives a poor experience as shown above. Especially if the user just set up the device, that would almost certainly mean it's available.

**Comment by valkaholic** [comment]
Got this to work for my L60, thank you!! I also have an L50 which seems nearly identical but it is not recognized. Any advice on how to port this over to the L50?

**Comment by ddakotac** [comment]
Amazing, thanks so much! Just go it working. Cheers maximoei!

**Comment by maximoei** [comment]
@valkaholic  -> T2275 version of L50 is included in the branch [details here](https://github.com/CodeFoodPixels/robovac/issues/42)

**Comment by cmdrpicard** [comment]
Thank you for doing this. Got my L60 SES working in HA.

**Comment by mumpers68** [comment]
Second that, much appreciated for the work on this!!On Oct 16, 2024, at 10:12 AM, cmdrpicard ***@***.***> wrote:﻿
Thank you for doing this. Got my L60 SES working in HA.

**Comment by Ali229** [comment]
@maximoei Is there a way to empty the bin into the base for L60? I got the vacuum working with your fork already btw. Another I have is emptied using a script like:

  ```
target:
    device_id:
      - 7fcaed7715dac05c823cab41cc95db1c
  data:
    command: setAutoEmpty
    params:
      act: start
  action: vacuum.send_command
```

**Comment by danielccm** [comment]
Maximoei, 

https://github.com/CodeFoodPixels/robovac/issues/85#issuecomment-2249935438

> Very much not supported:
> 
> * Room / Zone clean
> * Mopping related features
> * See map
> 

Any chance Room cleaning and Map seeing could be developed? Would be a game changer with the L60 SES... Just asking.. Great work btw!

**Comment by maximoei** [comment]
> @maximoei Is there a way to empty the bin into the base for L60? I got the vacuum working with your fork already btw. Another vacuum I have is emptied using a script like:
> 

This works for me to empty into the bin (but not the cutting action):

```
action: vacuum.send_command
data: 
  entity_id: vacuum.l60
  command: 173
  params:
    value: "BBICGAE="

```

**Comment by merkurmaniac** [comment]
@maximoei , thanks so much for your hard work on this.  It's much appreciated. 

Sorry to be so dumb on this, but are you saying above that the L50 vacuum is now again part of this fork, and doesn't need to be treated differently than the L60 ?  Just making sure I am reading this correctly.

**Comment by musicscoree96** [comment]
I added all the files from the github repo using the file manager from HA to the HA installation.
Then I added the Robovac to the device and added the IP-Adres. But the first time I click "configure" it kept on spinnen showing the screen "Edit vacum".  After minutes waiting I stop the recovery and click configure again. Then it kept on spinning showwing "One moment please while configuring Eufy Robovac is being in initializing". The only way to stop this if by removing the powerline from my RPI4 because clicking anywhere does not do anything.

I'm trying to add the L60. The file T2277 is available in the map. 

Please help

**Comment by valkaholic** [comment]
> @valkaholic -> T2275 version of L50 is included in the branch [details here](https://github.com/CodeFoodPixels/robovac/issues/42)

FYI I got the L50 working using this fork and adding T2265. For some reason it was never recognized with T2275.

**Comment by musicscoree96** [comment]
Thank you valkaholic. I managed to get it to work with the L60.
I missed 1 of the files in the vacuum map and thats why the add-on was not working and generated an error.
After copied ALL files to the vacuum map, the add on worked perfect.
Thank you for your reponse.

**Comment by merkurmaniac** [comment]
> > @valkaholic -> T2275 version of L50 is included in the branch [details here](https://github.com/CodeFoodPixels/robovac/issues/42)
> 
> FYI I got the L50 working using this fork and adding T2265. For some reason it was never recognized with T2275.

Where do I find the T2265 file ?  It was not in the big batch of them that I copied down.

**Comment by valkaholic** [comment]
> > > @valkaholic -> T2275 version of L50 is included in the branch [details here](https://github.com/CodeFoodPixels/robovac/issues/42)
> > 
> > 
> > FYI I got the L50 working using this fork and adding T2265. For some reason it was never recognized with T2275.
> 
> Where do I find the T2265 file ? It was not in the big batch of them that I copied down.

It's not in there. You can just duplicate the T2267 file and rename to T2265, and also change the reference in the code to T2265 (line 5). Add the reference to the _init_.py file (from .T2265 import T2265) and reboot. It should pick up the L50, but you will have to start the vacuum once from the Eufy app to get full functionality. Actually, I need to do that every time HA is reset.

**Comment by merkurmaniac** [comment]
Thank you @valkaholic  , I appreciate you taking the time to help out with that.  It was not too obvious to me.

**Comment by merkurmaniac** [comment]
Still cannot get it added.

I edited this file by changing line 5 to read "class T2265:" 

/homeassistant/custom_components/robovac/vacuums/T2265.py

I then edited this file: 
/homeassistant/custom_components/robovac/vacuums/__init__.py

by adding the 

from .T2265 import T2265

and later down adding 

"T2265": T2265,

Is there anything else I need to change ?  I launch it from the Eufy app and it only shows a single entry of battery that shows unavailable.

There is also another init__.py in the directory above this one.  Its here: 

/homeassistant/custom_components/robovac/__init__.py

I have NOT edited it at all.  Please advise if you see what I am doing wrong.

**Comment by valkaholic** [comment]
That should be everything. Before launching in the native Eufy app you configured the device in the Eufy Robovac integration?

**Comment by KEBAP5000** [comment]
> Should the developer read this, and willing to look into it. Some more messages from the device, when I start it via the Eufy app. It looks like it's encrypted. I noticed that '179' has 4 values which would match potential states the device is in. (positioning, cleaning, heading home, charging). These only reported after a first run tho.
> 
> {'151': True, '156': True, '158': 'Turbo', '159': True, '160': False, '161': 41, '163': 99, '177': 'DAjZhNCLlIztzgFSAA==', '153': 'BBADGgA=', '178': 'DQiuzqvylIztzgESAR8=', '152': 'AggG', '179': 'FhIUEhIIEBABIGMozsPsswYwgcTsswY=', '173': 'GAoSMgoKAggBEgQIARgPOgQKAggBEgIIAQ==', '176': 'JgoAGgBSCBoAIgIIASoAWDBiFAoSCghOcjE4X0lvVBoGEKnC7LMG', '169': 'xxx'}

@Harm-Veraa How did you intercept these commands?

Specifically, I would be interested in knowing which command code I would need for suction + haircut and how to make the robot clean different rooms.

**Comment by whitebaitonline** [comment]
Has anyone been able to look further into this and determine if the codes for the rest of the features could be decrypted in some way with enough analysis? I have an L60 SES and would love to be able to send it to certain rooms through HA, even if it's a bunch of trial and error to figure out the correct commands. Just wanted to know if someone else has spend time on this and determined its futile without more data than just what is logged in HA?
