### ISSUE TITLE
Not detecting the robovacs

### ISSUE THREAD

**Issue by Kk050505** [CodeFoodPixels/robovac#86]
Used to work when I had one vac in the account. Added one more and now both robovacs are not being detected right. None of the parameters appear. Tried multiple times to remove the custom repo, delete the integration, reboot HA. Still the same. 
Tried multiple versions of the repo including beta. 
Error as logged from log viewer -
File "/config/custom_components/robovac/vacuum.py", line 267, in __init__
    self._attr_supported_features = self.vacuum.getHomeAssistantFeatures()
                                    ^^^^^^^^^^^
AttributeError: 'RoboVacEntity' object has no attribute 'vacuum'

**Comment by Kk050505** [comment]
25c was the first one and it worked fine. Added X8 pro and nothing seems to work. Both vacs have no attributes/entities. Battery shows unknown and no other parameters are picked up.

**Comment by FelixJanemalm** [comment]
Same issue here with fresh installation.

1. Added new robovac (X10 Pro Omni) through the eufy Clean app
2. Freshly installed integration
3. Followed instructions and logged in using Eufy account credentials
4. No devices or entities detected in the integration
 
<img width="596" alt="image" src="https://github.com/CodeFoodPixels/robovac/assets/51474968/bb1f9268-0639-462d-9a8d-199a47558e50">

**Comment by Kk050505** [comment]
Recent error logged was this 
Logger: homeassistant.components.vacuum
Source: helpers/entity_platform.py:356
integration: Vacuum (documentation, issues)
First occurred: 11:06:29 PM (3 occurrences)
Last logged: 11:06:56 PM

Error while setting up robovac platform for vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/robovac/vacuum.py", line 116, in async_setup_entry
    entity = RoboVacEntity(item)
             ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/robovac/vacuum.py", line 284, in __init__
    self._attr_supported_features = self.vacuum.getHomeAssistantFeatures()
                                    ^^^^^^^^^^^
AttributeError: 'RoboVacEntity' object has no attribute 'vacuum'

**Comment by MartinBachmannHD** [comment]
...similar error in the vacuum.py with an X8 Hybrid - here is the log ( I am on the Beta):

2024-07-08T07:29:36.684104756Z 2024-07-08 09:29:36.681 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
2024-07-08T07:29:36.684151682Z Traceback (most recent call last):
2024-07-08T07:29:36.684159904Z   File "/config/custom_components/robovac/tuyalocalapi.py", line 806, in async_gratuitous_update_state
2024-07-08T07:29:36.684167107Z     await self.update_entity_state_cb()
2024-07-08T07:29:36.684173274Z   File "/config/custom_components/robovac/vacuum.py", line 330, in pushed_update_handler
2024-07-08T07:29:36.684179663Z     self.update_entity_values()
2024-07-08T07:29:36.684185385Z   File "/config/custom_components/robovac/vacuum.py", line 354, in update_entity_values
2024-07-08T07:29:36.684191459Z     self._tuya_command_codes[RobovacCommand.CLEANING_AREA]
2024-07-08T07:29:36.684197292Z     ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-08T07:29:36.684203052Z KeyError: <RobovacCommand.CLEANING_AREA: 'cleaning_area'>
